[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
heck.workspace = true
argh.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

smacktivity = { path = "../lib" }
smacktivity-network = { path = "../network" }

[[bin]]
name = "memes"
path = "src/memes.rs"

[[bin]]
name = "from-stdin"
path = "src/from-stdin.rs"
